
publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  container:
    image: google/cloud-sdk:latest
  environment:
    KEYFILE_SECRET: ENCRYPTED[20ee50241acdda4339b39ddfc931bdbf30a61021679847bedd0c0f223166814729723426dd3060fa77bc05a68a782bcf]
  script:
    - openssl enc -aes-256-cbc -d -in key.json.enc -out key.json -k $KEYFILE_SECRET
    - gcloud auth activate-service-account --key-file=key.json
    - gsutil cp content/* gs://npmdoc
